import type { Connection, SqlValue, Logger } from "espalier-jdbc";
import { LogLevel, getGlobalLogger } from "espalier-jdbc";
import type { EntityMetadata, FieldMapping } from "../mapping/entity-metadata.js";
import type { RowMapper } from "../mapping/row-mapper.js";
import { SelectBuilder, InsertBuilder, UpdateBuilder, DeleteBuilder } from "../query/query-builder.js";
import { ComparisonCriteria, LogicalCriteria } from "../query/criteria.js";
import { OptimisticLockException } from "./optimistic-lock.js";
import { EntityNotFoundException } from "./entity-not-found.js";
import type { EntityCache } from "../cache/entity-cache.js";
import type { QueryCache } from "../cache/query-cache.js";
import type { EntityChangeTracker } from "../mapping/change-tracker.js";
import type { LifecycleEvent } from "../decorators/lifecycle.js";
import type { EventBus } from "../events/event-bus.js";
import type { EntityPersistedEvent, EntityUpdatedEvent, EntityRemovedEvent } from "../events/entity-events.js";
import { ENTITY_EVENTS } from "../events/entity-events.js";
import type { OneToOneRelation } from "../decorators/relations.js";
import { getFieldValue } from "../mapping/field-access.js";
import type { CascadeManager } from "./cascade-manager.js";

export interface EntityPersisterDeps<T> {
  entityClass: new (...args: any[]) => T;
  metadata: EntityMetadata;
  rowMapper: RowMapper<T>;
  entityCache: EntityCache;
  queryCache: QueryCache;
  changeTracker: EntityChangeTracker<T>;
  eventBus: EventBus | undefined;
  tenantColumn: string | undefined;
  tenantIdField: string | symbol | undefined;
  isAutoGeneratedId: boolean;
  cascadeManager: CascadeManager<T>;
  getIdColumn: () => string;
  getEntityId: (entity: T) => unknown;
  getVersionColumn: () => string | undefined;
  requireTenantForWrite: () => string | undefined;
  tenantCacheKey: (id: unknown) => unknown;
  copyRelationFields: (target: T, source: T) => void;
  getOneToOneFkValue: (entity: T, relation: OneToOneRelation) => SqlValue | undefined;
  getManyToOneFkValue: (entity: T, relation: import("../decorators/relations.js").ManyToOneRelation) => SqlValue;
}

export class EntityPersister<T> {
  private readonly entityClass: new (...args: any[]) => T;
  private readonly metadata: EntityMetadata;
  private readonly rowMapper: RowMapper<T>;
  private readonly entityCache: EntityCache;
  private readonly queryCache: QueryCache;
  private readonly changeTracker: EntityChangeTracker<T>;
  private readonly eventBus: EventBus | undefined;
  private readonly tenantColumn: string | undefined;
  private readonly tenantIdField: string | symbol | undefined;
  private readonly isAutoGeneratedId: boolean;
  private readonly cascadeManager: CascadeManager<T>;
  private readonly getIdColumn: () => string;
  private readonly getEntityId: (entity: T) => unknown;
  private readonly getVersionColumn: () => string | undefined;
  private readonly requireTenantForWrite: () => string | undefined;
  private readonly tenantCacheKey: (id: unknown) => unknown;
  private readonly copyRelationFields: (target: T, source: T) => void;
  private readonly getOneToOneFkValue: (entity: T, relation: OneToOneRelation) => SqlValue | undefined;
  private readonly getManyToOneFkValue: (entity: T, relation: import("../decorators/relations.js").ManyToOneRelation) => SqlValue;
  private readonly entityName: string;
  private readonly repoLogger: Logger;

  constructor(deps: EntityPersisterDeps<T>) {
    this.entityClass = deps.entityClass;
    this.metadata = deps.metadata;
    this.rowMapper = deps.rowMapper;
    this.entityCache = deps.entityCache;
    this.queryCache = deps.queryCache;
    this.changeTracker = deps.changeTracker;
    this.eventBus = deps.eventBus;
    this.tenantColumn = deps.tenantColumn;
    this.tenantIdField = deps.tenantIdField;
    this.isAutoGeneratedId = deps.isAutoGeneratedId;
    this.cascadeManager = deps.cascadeManager;
    this.getIdColumn = deps.getIdColumn;
    this.getEntityId = deps.getEntityId;
    this.getVersionColumn = deps.getVersionColumn;
    this.requireTenantForWrite = deps.requireTenantForWrite;
    this.tenantCacheKey = deps.tenantCacheKey;
    this.copyRelationFields = deps.copyRelationFields;
    this.getOneToOneFkValue = deps.getOneToOneFkValue;
    this.getManyToOneFkValue = deps.getManyToOneFkValue;
    this.entityName = deps.entityClass.name;
    this.repoLogger = getGlobalLogger().child("repository");
  }

  async invokeLifecycleCallbacks(entity: T, event: LifecycleEvent): Promise<void> {
    const methods = this.metadata.lifecycleCallbacks.get(event);
    if (!methods) return;
    if (this.repoLogger.isEnabled(LogLevel.TRACE)) {
      this.repoLogger.trace("lifecycle callback", { entityType: this.entityName, event });
    }
    for (const methodName of methods) {
      const result = (entity as Record<string | symbol, (...args: any[]) => any>)[methodName].call(entity);
      if (result instanceof Promise) {
        await result;
      }
    }
  }

  async emitEntityEvent(genericEvent: string, specificEvent: string, payload: unknown): Promise<void> {
    if (!this.eventBus) return;
    await this.eventBus.emit(genericEvent, payload);
    await this.eventBus.emit(specificEvent, payload);
  }

  async saveWithConnection(entity: T, conn: Connection): Promise<T> {
    const cascadeSaving = new Set<unknown>();
    return this.saveWithConnectionInternal(entity, conn, cascadeSaving);
  }

  async saveWithConnectionInternal(entity: T, conn: Connection, cascadeSaving: Set<unknown>): Promise<T> {
    const idField = this.metadata.idField;
    const idValue = (entity as Record<string | symbol, unknown>)[idField] as SqlValue;
    const idCol = this.getIdColumn();
    const versionCol = this.getVersionColumn();
    const versionField = this.metadata.versionField;

    if (cascadeSaving.has(entity)) return entity;
    cascadeSaving.add(entity);

    try {
      await this.cascadeManager.cascadePreSave(entity, conn, cascadeSaving);

      const isNewEntity = idValue == null || (this.isAutoGeneratedId && (idValue === 0 || idValue === ""));

      if (!isNewEntity) {
        return await this.performUpdate(entity, conn, cascadeSaving, idField, idValue, idCol, versionCol, versionField);
      } else {
        return await this.performInsert(entity, conn, cascadeSaving, idField, idCol, versionCol, versionField);
      }
    } finally {
      cascadeSaving.delete(entity);
    }
  }

  private async performUpdate(
    entity: T, conn: Connection, cascadeSaving: Set<unknown>,
    idField: string | symbol, idValue: SqlValue, idCol: string,
    versionCol: string | undefined, versionField: string | symbol | undefined,
  ): Promise<T> {
    if (this.metadata.lastModifiedDateField) {
      (entity as Record<string | symbol, unknown>)[this.metadata.lastModifiedDateField] = new Date();
    }
    await this.invokeLifecycleCallbacks(entity, "PreUpdate");

    const hasSnapshot = this.changeTracker.getSnapshot(entity) !== undefined;
    const dirtyFields = hasSnapshot ? this.changeTracker.getDirtyFields(entity) : [];
    const isFullUpdate = !hasSnapshot;

    if (hasSnapshot && dirtyFields.length === 0) {
      const hasCascadeRelations =
        this.metadata.oneToManyRelations.some(r => r.cascade.has("persist") || r.cascade.has("merge")) ||
        this.metadata.manyToManyRelations.some(r => r.cascade.has("persist") || r.cascade.has("merge")) ||
        this.metadata.oneToOneRelations.some(r => r.cascade.has("persist") || r.cascade.has("merge")) ||
        this.metadata.manyToOneRelations.some(r => r.cascade.has("persist") || r.cascade.has("merge"));
      if (hasCascadeRelations) {
        await this.cascadeManager.cascadePostSave(entity, conn, cascadeSaving);
      }
      return entity;
    }

    const updateBuilder = new UpdateBuilder(this.metadata.tableName);

    let currentVersion: number | undefined;
    if (versionField && versionCol) {
      currentVersion = (entity as Record<string | symbol, unknown>)[versionField] as number;
      const newVersion = (currentVersion ?? 0) + 1;
      updateBuilder.where(
        new LogicalCriteria(
          "and",
          new ComparisonCriteria("eq", idCol, idValue),
          new ComparisonCriteria("eq", versionCol, currentVersion as SqlValue),
        ),
      );

      if (isFullUpdate) {
        for (const field of this.metadata.fields) {
          if (field.fieldName === idField) continue;
          if (field.fieldName === versionField) {
            updateBuilder.set(field.columnName, newVersion as SqlValue);
          } else {
            const value = getFieldValue(entity as Record<string | symbol, unknown>, field.fieldName) as SqlValue;
            updateBuilder.set(field.columnName, value);
          }
        }
        for (const relation of this.metadata.oneToOneRelations) {
          const fkValue = this.getOneToOneFkValue(entity, relation);
          if (fkValue !== undefined && relation.joinColumn) {
            updateBuilder.set(relation.joinColumn, fkValue);
          }
        }
        for (const relation of this.metadata.manyToOneRelations) {
          const fkValue = this.getManyToOneFkValue(entity, relation);
          updateBuilder.set(relation.joinColumn, fkValue);
        }
      } else {
        updateBuilder.set(versionCol, newVersion as SqlValue);
        const dirtyColumnNames = new Set(dirtyFields.map((c) => c.columnName));
        for (const change of dirtyFields) {
          if (change.field === idField || change.field === versionField) continue;
          updateBuilder.set(change.columnName, change.newValue as SqlValue);
        }
        for (const relation of this.metadata.oneToOneRelations) {
          if (!relation.isOwning || !relation.joinColumn) continue;
          if (dirtyColumnNames.has(relation.joinColumn)) continue;
          const fkValue = this.getOneToOneFkValue(entity, relation);
          if (fkValue !== undefined) {
            updateBuilder.set(relation.joinColumn, fkValue);
          }
        }
        for (const relation of this.metadata.manyToOneRelations) {
          if (dirtyColumnNames.has(relation.joinColumn)) continue;
          const fkValue = this.getManyToOneFkValue(entity, relation);
          updateBuilder.set(relation.joinColumn, fkValue);
        }
      }
    } else {
      updateBuilder.where(new ComparisonCriteria("eq", idCol, idValue));

      if (isFullUpdate) {
        for (const field of this.metadata.fields) {
          if (field.fieldName === idField) continue;
          const value = getFieldValue(entity as Record<string | symbol, unknown>, field.fieldName) as SqlValue;
          updateBuilder.set(field.columnName, value);
        }
        for (const relation of this.metadata.oneToOneRelations) {
          const fkValue = this.getOneToOneFkValue(entity, relation);
          if (fkValue !== undefined && relation.joinColumn) {
            updateBuilder.set(relation.joinColumn, fkValue);
          }
        }
        for (const relation of this.metadata.manyToOneRelations) {
          const fkValue = this.getManyToOneFkValue(entity, relation);
          updateBuilder.set(relation.joinColumn, fkValue);
        }
      } else {
        const dirtyColumnNames = new Set(dirtyFields.map((c) => c.columnName));
        for (const change of dirtyFields) {
          if (change.field === idField) continue;
          updateBuilder.set(change.columnName, change.newValue as SqlValue);
        }
        for (const relation of this.metadata.oneToOneRelations) {
          if (!relation.isOwning || !relation.joinColumn) continue;
          if (dirtyColumnNames.has(relation.joinColumn)) continue;
          const fkValue = this.getOneToOneFkValue(entity, relation);
          if (fkValue !== undefined) {
            updateBuilder.set(relation.joinColumn, fkValue);
          }
        }
        for (const relation of this.metadata.manyToOneRelations) {
          if (dirtyColumnNames.has(relation.joinColumn)) continue;
          const fkValue = this.getManyToOneFkValue(entity, relation);
          updateBuilder.set(relation.joinColumn, fkValue);
        }
      }
    }

    if (this.tenantColumn) {
      const tid = this.requireTenantForWrite();
      if (tid !== undefined) {
        updateBuilder.and(new ComparisonCriteria("eq", this.tenantColumn, tid as SqlValue));
      }
    }
    updateBuilder.returning("*");

    const query = updateBuilder.build();
    const stmt = conn.prepareStatement(query.sql);
    try {
      for (let i = 0; i < query.params.length; i++) {
        stmt.setParameter(i + 1, query.params[i]);
      }
      const rs = await stmt.executeQuery();
      if (await rs.next()) {
        const saved = this.rowMapper.mapRow(rs);
        this.copyRelationFields(saved, entity);
        cascadeSaving.add(saved);
        await this.cascadeManager.cascadePostSave(saved, conn, cascadeSaving);
        await this.invokeLifecycleCallbacks(saved, "PostUpdate");
        this.changeTracker.snapshot(saved);
        this.entityCache.evict(this.entityClass, this.tenantCacheKey(this.getEntityId(saved)));
        this.queryCache.invalidate(this.entityClass);
        await this.emitEntityEvent(ENTITY_EVENTS.UPDATED, `${ENTITY_EVENTS.UPDATED}:${this.entityName}`, {
          type: "updated",
          entityClass: this.entityClass,
          entityName: this.entityName,
          entity: saved,
          id: this.getEntityId(saved),
          changes: hasSnapshot ? dirtyFields : undefined,
          timestamp: new Date(),
        } satisfies EntityUpdatedEvent<T>);
        return saved;
      }

      if (versionField && versionCol && currentVersion !== undefined) {
        this.entityCache.evict(this.entityClass, this.tenantCacheKey(idValue));
        let actualVersion: number | null = null;
        const checkQuery = new SelectBuilder(this.metadata.tableName)
          .columns(versionCol)
          .where(new ComparisonCriteria("eq", idCol, idValue))
          .limit(1)
          .build();
        const checkStmt = conn.prepareStatement(checkQuery.sql);
        try {
          for (let pi = 0; pi < checkQuery.params.length; pi++) {
            checkStmt.setParameter(pi + 1, checkQuery.params[pi]);
          }
          const checkRs = await checkStmt.executeQuery();
          if (await checkRs.next()) {
            const row = checkRs.getRow();
            const val = Object.values(row)[0];
            actualVersion = typeof val === "number" ? val : Number(val);
          }
        } finally {
          await checkStmt.close().catch(() => {});
        }
        throw new OptimisticLockException(
          this.entityClass.name,
          idValue,
          currentVersion,
          actualVersion,
        );
      }

      this.entityCache.evict(this.entityClass, this.tenantCacheKey(idValue));
      this.queryCache.invalidate(this.entityClass);
      this.changeTracker.clearSnapshot(entity);
      throw new EntityNotFoundException(this.entityClass.name, idValue);
    } finally {
      await stmt.close().catch(() => {});
    }
  }

  private async performInsert(
    entity: T, conn: Connection, cascadeSaving: Set<unknown>,
    idField: string | symbol, idCol: string,
    versionCol: string | undefined, versionField: string | symbol | undefined,
  ): Promise<T> {
    if (this.tenantIdField && this.tenantColumn) {
      const tid = this.requireTenantForWrite();
      if (tid !== undefined) {
        (entity as Record<string | symbol, unknown>)[this.tenantIdField] = tid;
      }
    }

    const now = new Date();
    if (this.metadata.createdDateField) {
      const currentVal = (entity as Record<string | symbol, unknown>)[this.metadata.createdDateField];
      if (currentVal === undefined || currentVal === null) {
        (entity as Record<string | symbol, unknown>)[this.metadata.createdDateField] = now;
      }
    }
    if (this.metadata.lastModifiedDateField) {
      (entity as Record<string | symbol, unknown>)[this.metadata.lastModifiedDateField] = now;
    }

    await this.invokeLifecycleCallbacks(entity, "PrePersist");
    const insertBuilder = new InsertBuilder(this.metadata.tableName);

    for (const field of this.metadata.fields) {
      if (field.fieldName === idField) continue;
      if (versionField && field.fieldName === versionField) {
        insertBuilder.set(field.columnName, 1 as SqlValue);
      } else {
        const value = getFieldValue(entity as Record<string | symbol, unknown>, field.fieldName) as SqlValue;
        insertBuilder.set(field.columnName, value);
      }
    }

    for (const relation of this.metadata.oneToOneRelations) {
      const fkValue = this.getOneToOneFkValue(entity, relation);
      if (fkValue !== undefined && relation.joinColumn) {
        insertBuilder.set(relation.joinColumn, fkValue);
      }
    }

    for (const relation of this.metadata.manyToOneRelations) {
      const fkValue = this.getManyToOneFkValue(entity, relation);
      insertBuilder.set(relation.joinColumn, fkValue);
    }

    insertBuilder.returning("*");

    const query = insertBuilder.build();
    const stmt = conn.prepareStatement(query.sql);
    try {
      for (let i = 0; i < query.params.length; i++) {
        stmt.setParameter(i + 1, query.params[i]);
      }
      const rs = await stmt.executeQuery();
      if (await rs.next()) {
        const saved = this.rowMapper.mapRow(rs);
        this.copyRelationFields(saved, entity);
        cascadeSaving.add(saved);
        await this.cascadeManager.cascadePostSave(saved, conn, cascadeSaving);
        await this.invokeLifecycleCallbacks(saved, "PostPersist");
        this.changeTracker.snapshot(saved);
        this.entityCache.evict(this.entityClass, this.tenantCacheKey(this.getEntityId(saved)));
        this.queryCache.invalidate(this.entityClass);
        await this.emitEntityEvent(ENTITY_EVENTS.PERSISTED, `${ENTITY_EVENTS.PERSISTED}:${this.entityName}`, {
          type: "persisted",
          entityClass: this.entityClass,
          entityName: this.entityName,
          entity: saved,
          id: this.getEntityId(saved),
          timestamp: new Date(),
        } satisfies EntityPersistedEvent<T>);
        return saved;
      }
      return entity;
    } finally {
      await stmt.close().catch(() => {});
    }
  }

  async deleteWithConnection(entity: T, conn: Connection): Promise<void> {
    const cascadeDeleting = new Set<unknown>();

    await this.invokeLifecycleCallbacks(entity, "PreRemove");
    const idField = this.metadata.idField;
    const idValue = (entity as Record<string | symbol, unknown>)[idField] as SqlValue;
    const idCol = this.getIdColumn();
    const versionCol = this.getVersionColumn();
    const versionField = this.metadata.versionField;

    await this.cascadeManager.cascadePreDelete(entity, conn, cascadeDeleting);

    const builder = new DeleteBuilder(this.metadata.tableName);

    let currentVersion: number | undefined;
    if (versionField && versionCol) {
      currentVersion = (entity as Record<string | symbol, unknown>)[versionField] as number;
      builder.where(
        new LogicalCriteria(
          "and",
          new ComparisonCriteria("eq", idCol, idValue),
          new ComparisonCriteria("eq", versionCol, currentVersion as SqlValue),
        ),
      );
    } else {
      builder.where(new ComparisonCriteria("eq", idCol, idValue));
    }
    this.applyTenantFilter(builder);

    const query = builder.build();
    const stmt = conn.prepareStatement(query.sql);
    try {
      for (let i = 0; i < query.params.length; i++) {
        stmt.setParameter(i + 1, query.params[i]);
      }
      const affected = await stmt.executeUpdate();
      if (versionField && versionCol && currentVersion !== undefined && affected === 0) {
        let actualVersion: number | null = null;
        const checkQuery = new SelectBuilder(this.metadata.tableName)
          .columns(versionCol)
          .where(new ComparisonCriteria("eq", idCol, idValue))
          .limit(1)
          .build();
        const checkStmt = conn.prepareStatement(checkQuery.sql);
        try {
          for (let pi = 0; pi < checkQuery.params.length; pi++) {
            checkStmt.setParameter(pi + 1, checkQuery.params[pi]);
          }
          const checkRs = await checkStmt.executeQuery();
          if (await checkRs.next()) {
            const row = checkRs.getRow();
            const val = Object.values(row)[0];
            actualVersion = typeof val === "number" ? val : Number(val);
          }
        } finally {
          await checkStmt.close().catch(() => {});
        }
        throw new OptimisticLockException(
          this.entityClass.name,
          idValue,
          currentVersion,
          actualVersion,
        );
      }
      await this.invokeLifecycleCallbacks(entity, "PostRemove");
      await this.cascadeManager.cascadePostDelete(entity, conn, cascadeDeleting);
      await this.emitEntityEvent(ENTITY_EVENTS.REMOVED, `${ENTITY_EVENTS.REMOVED}:${this.entityName}`, {
        type: "removed",
        entityClass: this.entityClass,
        entityName: this.entityName,
        entity,
        id: idValue,
        timestamp: new Date(),
      } satisfies EntityRemovedEvent<T>);
      this.changeTracker.clearSnapshot(entity);
      this.entityCache.evict(this.entityClass, this.tenantCacheKey(idValue));
      this.queryCache.invalidate(this.entityClass);
    } finally {
      await stmt.close().catch(() => {});
    }
  }

  applyTenantFilter(builder: { and(criteria: import("../query/criteria.js").Criteria): unknown }): void {
    const tid = this.requireTenantForWrite();
    if (!tid || !this.tenantColumn) return;
    builder.and(new ComparisonCriteria("eq", this.tenantColumn, tid as SqlValue));
  }
}
