import type { PlaygroundExample } from "./types.js";

export const builtInExamples: PlaygroundExample[] = [
  {
    id: "hello-world",
    title: "Hello World",
    description: "Basic entity CRUD operations: create a table, insert rows, query, update, and delete.",
    category: "basics",
    code: [
      "-- Create a simple users table",
      "CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT NOT NULL, email TEXT UNIQUE)",
      "",
      "-- Insert some data",
      "INSERT INTO users (id, name, email) VALUES (1, 'Alice', 'alice@example.com')",
      "INSERT INTO users (id, name, email) VALUES (2, 'Bob', 'bob@example.com')",
      "",
      "-- Query all users",
      "SELECT * FROM users",
    ].join("\n"),
    difficulty: "beginner",
  },
  {
    id: "relations",
    title: "Relations",
    description: "OneToMany and ManyToMany relationships between entities using foreign keys and join tables.",
    category: "relations",
    code: [
      "-- OneToMany: Author has many Books",
      "CREATE TABLE authors (id INTEGER PRIMARY KEY, name TEXT NOT NULL)",
      "CREATE TABLE books (id INTEGER PRIMARY KEY, title TEXT NOT NULL, author_id INTEGER REFERENCES authors(id))",
      "",
      "-- ManyToMany: Books and Tags via join table",
      "CREATE TABLE tags (id INTEGER PRIMARY KEY, label TEXT NOT NULL)",
      "CREATE TABLE book_tags (book_id INTEGER REFERENCES books(id), tag_id INTEGER REFERENCES tags(id), PRIMARY KEY (book_id, tag_id))",
      "",
      "INSERT INTO authors (id, name) VALUES (1, 'J.K. Rowling')",
      "INSERT INTO books (id, title, author_id) VALUES (1, 'Harry Potter', 1)",
      "INSERT INTO tags (id, label) VALUES (1, 'fantasy')",
      "INSERT INTO book_tags (book_id, tag_id) VALUES (1, 1)",
      "",
      "-- Join query",
      "SELECT b.title, a.name AS author, t.label AS tag FROM books b JOIN authors a ON b.author_id = a.id JOIN book_tags bt ON bt.book_id = b.id JOIN tags t ON t.id = bt.tag_id",
    ].join("\n"),
    difficulty: "intermediate",
  },
  {
    id: "derived-queries",
    title: "Derived Queries",
    description: "Simulating derived query patterns like findByName and findByAgeGreaterThan using SQL.",
    category: "queries",
    code: [
      "CREATE TABLE people (id INTEGER PRIMARY KEY, name TEXT NOT NULL, age INTEGER NOT NULL, city TEXT)",
      "",
      "INSERT INTO people (id, name, age, city) VALUES (1, 'Alice', 30, 'New York')",
      "INSERT INTO people (id, name, age, city) VALUES (2, 'Bob', 25, 'London')",
      "INSERT INTO people (id, name, age, city) VALUES (3, 'Charlie', 35, 'New York')",
      "INSERT INTO people (id, name, age, city) VALUES (4, 'Diana', 28, 'Paris')",
      "",
      "-- findByName",
      "SELECT * FROM people WHERE name = 'Alice'",
      "",
      "-- findByAgeGreaterThan",
      "SELECT * FROM people WHERE age > 27",
    ].join("\n"),
    difficulty: "beginner",
  },
  {
    id: "specifications",
    title: "Specifications",
    description: "Composable query predicates using WHERE clauses combined with AND/OR.",
    category: "queries",
    code: [
      "CREATE TABLE products (id INTEGER PRIMARY KEY, name TEXT, price REAL, category TEXT, in_stock INTEGER)",
      "",
      "INSERT INTO products (id, name, price, category, in_stock) VALUES (1, 'Laptop', 999.99, 'electronics', 1)",
      "INSERT INTO products (id, name, price, category, in_stock) VALUES (2, 'Book', 19.99, 'books', 1)",
      "INSERT INTO products (id, name, price, category, in_stock) VALUES (3, 'Headphones', 149.99, 'electronics', 0)",
      "INSERT INTO products (id, name, price, category, in_stock) VALUES (4, 'Pen', 2.99, 'office', 1)",
      "",
      "-- Specification: electronics AND in_stock",
      "SELECT * FROM products WHERE category = 'electronics' AND in_stock = 1",
      "",
      "-- Specification: price < 20 OR category = 'office'",
      "SELECT * FROM products WHERE price < 20 OR category = 'office'",
    ].join("\n"),
    difficulty: "intermediate",
  },
  {
    id: "soft-delete",
    title: "Soft Delete",
    description: "Implementing @SoftDelete pattern with a deleted_at column and restore capability.",
    category: "patterns",
    code: [
      "CREATE TABLE documents (id INTEGER PRIMARY KEY, title TEXT NOT NULL, content TEXT, deleted_at TEXT DEFAULT NULL)",
      "",
      "INSERT INTO documents (id, title, content) VALUES (1, 'Report Q1', 'Quarterly results...')",
      "INSERT INTO documents (id, title, content) VALUES (2, 'Draft Memo', 'Internal memo...')",
      "",
      "-- Soft delete a document",
      "UPDATE documents SET deleted_at = datetime('now') WHERE id = 2",
      "",
      "-- Query only active documents (not soft-deleted)",
      "SELECT * FROM documents WHERE deleted_at IS NULL",
      "",
      "-- Restore soft-deleted document",
      "UPDATE documents SET deleted_at = NULL WHERE id = 2",
      "",
      "-- Verify restore",
      "SELECT * FROM documents WHERE deleted_at IS NULL",
    ].join("\n"),
    difficulty: "intermediate",
  },
  {
    id: "audit-trail",
    title: "Audit Trail",
    description: "Implementing @Audited entity pattern with created_at, updated_at, and created_by columns.",
    category: "patterns",
    code: [
      "CREATE TABLE audit_records (id INTEGER PRIMARY KEY, entity_name TEXT NOT NULL, entity_id INTEGER NOT NULL, action TEXT NOT NULL, changed_by TEXT, changed_at TEXT DEFAULT (datetime('now')), old_values TEXT, new_values TEXT)",
      "",
      "CREATE TABLE orders (id INTEGER PRIMARY KEY, product TEXT NOT NULL, quantity INTEGER NOT NULL, status TEXT DEFAULT 'pending', created_at TEXT DEFAULT (datetime('now')), updated_at TEXT DEFAULT (datetime('now')), created_by TEXT DEFAULT 'system')",
      "",
      "-- Create an order",
      "INSERT INTO orders (id, product, quantity, created_by) VALUES (1, 'Widget', 10, 'admin')",
      "",
      "-- Log the creation in audit trail",
      "INSERT INTO audit_records (id, entity_name, entity_id, action, changed_by, old_values, new_values) VALUES (1, 'orders', 1, 'INSERT', 'admin', NULL, '{\"product\":\"Widget\",\"quantity\":10}')",
      "",
      "-- Update the order",
      "UPDATE orders SET status = 'shipped', updated_at = datetime('now') WHERE id = 1",
      "",
      "-- Log the update",
      "INSERT INTO audit_records (id, entity_name, entity_id, action, changed_by, old_values, new_values) VALUES (2, 'orders', 1, 'UPDATE', 'admin', '{\"status\":\"pending\"}', '{\"status\":\"shipped\"}')",
      "",
      "-- View audit trail",
      "SELECT * FROM audit_records ORDER BY changed_at",
    ].join("\n"),
    difficulty: "advanced",
  },
];
